"""
ProtoPatch — Git Service
Automates GitHub PR creation using PyGithub and dulwich.

Workflow:
  1. Parse GitHub repo URL to get owner/repo
  2. Clone repo (or reuse existing clone from AST engine)
  3. Create branch fix/protopatch-<timestamp>
  4. Write patch to matched files
  5. Commit with structured message
  6. Push branch
  7. Open Pull Request with rich Markdown body
"""
import logging
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent
from typing import Optional

logger = logging.getLogger(__name__)


class GitService:
    """
    Automates branch creation, patching, and PR opening on GitHub.
    Uses PyGithub for GitHub API operations.
    """

    def __init__(self, github_token: str):
        self.github_token = github_token
        self._github = None

    def _get_github(self):
        """Lazy-initialize PyGithub client."""
        if self._github is None:
            try:
                from github import Github
                self._github = Github(self.github_token)
            except ImportError:
                raise ImportError(
                    "PyGithub is not installed. Run: pip install PyGithub"
                )
        return self._github

    def _parse_repo_url(self, repo_url: str) -> tuple[str, str]:
        """
        Parse GitHub URL to (owner, repo_name).
        Handles: https://github.com/owner/repo, https://github.com/owner/repo.git
        """
        url = repo_url.rstrip("/").removesuffix(".git")
        match = re.search(r"github\.com[/:]([^/]+)/([^/]+)$", url)
        if not match:
            raise ValueError(f"Could not parse GitHub URL: {repo_url}")
        return match.group(1), match.group(2)

    def _generate_pr_body(
        self,
        bug_analysis: dict,
        file_matches: list[dict],
        transcript: str,
        branch_name: str,
    ) -> str:
        """Generate professional Markdown PR body."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        target_element = bug_analysis.get("target_element", "Unknown")
        bug_description = bug_analysis.get("bug_description", "")
        suggested_fix = bug_analysis.get("suggested_fix", "")
        diff = bug_analysis.get("css_or_logic_diff", "")

        files_section = ""
        if file_matches:
            files_section = "\n".join(
                f"- `{m['file_path']}` (line {m.get('start_line', '?')}, "
                f"confidence: {int(m.get('score', 0))}%)"
                for m in file_matches[:3]
            )
        else:
            files_section = "_No specific file matched — review diff manually._"

        transcript_section = (
            f"> 🎙️ \"{transcript[:500]}\"" if transcript else "_No voice memo provided._"
        )

        diff_section = (
            f"```diff\n{diff}\n```" if diff else "_Diff generation pending — review suggested fix above._"
        )

        return dedent(f"""\
            ## 🩺 ProtoPatch — Automated Bug Fix

            > _Generated by [ProtoPatch](https://proto.patch) on {now}_

            ---

            ### 🐛 Bug Description

            {bug_description}

            **Target Element:** `{target_element}`

            ---

            ### 🎙️ Developer Voice Memo Transcript

            {transcript_section}

            ---

            ### 🔍 Files Affected

            {files_section}

            ---

            ### ✅ Suggested Fix

            {suggested_fix}

            ---

            ### 📋 Unified Diff

            {diff_section}

            ---

            ### 🧪 Testing Notes

            - [ ] Visual regression test on affected component
            - [ ] Cross-browser check (Chrome, Firefox, Safari)
            - [ ] Mobile responsiveness check on 375px, 768px viewports
            - [ ] Accessibility audit (axe-core or Lighthouse)

            ---

            ### 📊 ProtoPatch Metadata

            | Key | Value |
            |-----|-------|
            | Branch | `{branch_name}` |
            | Engine | ProtoPatch v1.0 |
            | VLM | Gemini 1.5 Flash |
            | AST | Tree-sitter |
            | Generated | {now} |

            ---

            _This PR was automatically generated by ProtoPatch. Please review the diff carefully before merging._
        """)

    def create_fix_pr(
        self,
        repo_url: str,
        base_branch: str,
        bug_analysis: dict,
        file_matches: list[dict],
        transcript: str = "",
        tmp_dir: Optional[Path] = None,
    ) -> dict:
        """
        Create a GitHub PR with the fix for the detected bug.

        Args:
            repo_url:     GitHub HTTPS URL
            base_branch:  Branch to create PR against (e.g. "main")
            bug_analysis: Dict from VisionService
            file_matches: List of matched file locations from ASTEngine
            transcript:   Whisper transcript of voice memo
            tmp_dir:      Temp directory (may contain cloned repo)

        Returns:
            {
                "pr_url": str,
                "pr_number": int,
                "branch_name": str,
            }
        """
        owner, repo_name = self._parse_repo_url(repo_url)
        timestamp = int(time.time())
        branch_name = f"fix/protopatch-{timestamp}"
        diff = bug_analysis.get("css_or_logic_diff", "")

        g = self._get_github()

        try:
            repo = g.get_repo(f"{owner}/{repo_name}")
        except Exception as exc:
            raise ValueError(f"Cannot access GitHub repo {owner}/{repo_name}: {exc}") from exc

        # Get base branch SHA
        try:
            base_ref = repo.get_branch(base_branch)
            base_sha = base_ref.commit.sha
        except Exception:
            # Try "master" as fallback
            try:
                base_ref = repo.get_branch("master")
                base_sha = base_ref.commit.sha
                base_branch = "master"
            except Exception as exc:
                raise ValueError(f"Cannot find base branch '{base_branch}' or 'master': {exc}") from exc

        # Create new branch
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_sha,
            )
            logger.info("Created branch: %s (from %s @ %s)", branch_name, base_branch, base_sha[:8])
        except Exception as exc:
            raise RuntimeError(f"Failed to create branch {branch_name}: {exc}") from exc

        # Apply patch to matched files (if diff is parseable)
        self._apply_patch_to_repo(repo, branch_name, diff, file_matches, bug_analysis)

        # Create Pull Request
        pr_title = f"🩺 fix: {bug_analysis.get('target_element', 'UI bug')} — ProtoPatch auto-fix"
        pr_body = self._generate_pr_body(
            bug_analysis=bug_analysis,
            file_matches=file_matches,
            transcript=transcript,
            branch_name=branch_name,
        )

        try:
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=base_branch,
                draft=False,
            )
            logger.info("PR created: #%d — %s", pr.number, pr.html_url)
            return {
                "pr_url": pr.html_url,
                "pr_number": pr.number,
                "branch_name": branch_name,
            }
        except Exception as exc:
            logger.error("PR creation failed: %s", exc)
            # Return partial result — branch exists even if PR failed
            return {
                "pr_url": f"{repo_url}/compare/{branch_name}",
                "pr_number": None,
                "branch_name": branch_name,
            }

    def _apply_patch_to_repo(
        self,
        repo,
        branch_name: str,
        diff: str,
        file_matches: list[dict],
        bug_analysis: dict,
    ):
        """
        Apply the fix diff to the repository via GitHub API.
        If a structured diff is available, parse and apply it.
        Otherwise, add a PATCH_NOTES.md with the fix instructions.
        """
        commit_message = (
            f"fix: apply ProtoPatch auto-fix\n\n"
            f"Bug: {bug_analysis.get('bug_description', '')[:200]}\n"
            f"Target: {bug_analysis.get('target_element', '')}\n"
            f"Fix: {bug_analysis.get('suggested_fix', '')[:200]}\n\n"
            f"Generated by ProtoPatch v1.0"
        )

        # Try to apply the diff to the first matched file
        applied = False
        if diff and file_matches:
            applied = self._try_apply_unified_diff(
                repo, branch_name, diff, file_matches[0], commit_message
            )

        # Fallback: write a PATCH_NOTES.md with all details
        if not applied:
            patch_notes = self._generate_patch_notes(bug_analysis, diff, file_matches)
            try:
                repo.create_file(
                    path="PROTOPATCH_FIX.md",
                    message=commit_message,
                    content=patch_notes,
                    branch=branch_name,
                )
                logger.info("Created PROTOPATCH_FIX.md on branch %s", branch_name)
            except Exception as exc:
                logger.warning("Could not write patch notes: %s", exc)

    def _try_apply_unified_diff(
        self,
        repo,
        branch_name: str,
        diff: str,
        file_match: dict,
        commit_message: str,
    ) -> bool:
        """
        Parse a unified diff and apply it to the target file via GitHub API.
        Returns True if successful.
        """
        try:
            # Extract target file path from diff header or file_match
            target_path = self._extract_diff_target(diff) or file_match.get("file_path", "")
            if not target_path:
                return False

            # Get current file content
            file_content = repo.get_contents(target_path, ref=branch_name)
            original_lines = file_content.decoded_content.decode("utf-8").split("\n")

            # Apply the diff
            patched_lines = self._apply_diff_lines(original_lines, diff)
            patched_content = "\n".join(patched_lines)

            # Commit the change
            repo.update_file(
                path=target_path,
                message=commit_message,
                content=patched_content,
                sha=file_content.sha,
                branch=branch_name,
            )
            logger.info("Applied diff to %s on branch %s", target_path, branch_name)
            return True

        except Exception as exc:
            logger.warning("Diff application failed: %s", exc)
            return False

    def _extract_diff_target(self, diff: str) -> Optional[str]:
        """Extract the target file path from a unified diff header."""
        # +++ b/src/components/Header.jsx → src/components/Header.jsx
        match = re.search(r"^\+\+\+\s+b?/?(.*)", diff, re.MULTILINE)
        if match:
            path = match.group(1).strip()
            return path if path and not path.startswith("/dev/null") else None
        return None

    def _apply_diff_lines(self, original_lines: list[str], diff: str) -> list[str]:
        """
        Apply a simple unified diff to lines. Handles basic +/- operations.
        Falls back to returning original + appended diff as comment if parsing fails.
        """
        try:
            result = list(original_lines)
            hunk_pattern = re.compile(r"@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")
            diff_lines = diff.split("\n")

            offset = 0
            i = 0
            while i < len(diff_lines):
                line = diff_lines[i]
                hunk = hunk_pattern.match(line)
                if hunk:
                    orig_start = int(hunk.group(1)) - 1
                    new_start = int(hunk.group(3)) - 1
                    i += 1

                    while i < len(diff_lines) and not diff_lines[i].startswith("@@"):
                        dl = diff_lines[i]
                        if dl.startswith("+") and not dl.startswith("+++"):
                            result.insert(new_start + offset, dl[1:])
                            offset += 1
                        elif dl.startswith("-") and not dl.startswith("---"):
                            if 0 <= (orig_start + offset) < len(result):
                                result.pop(orig_start + offset)
                                offset -= 1
                        i += 1
                else:
                    i += 1

            return result
        except Exception:
            return original_lines

    def _generate_patch_notes(
        self,
        bug_analysis: dict,
        diff: str,
        file_matches: list[dict],
    ) -> str:
        """Generate PROTOPATCH_FIX.md content."""
        files = "\n".join(
            f"- `{m['file_path']}` (line {m.get('start_line', '?')})"
            for m in file_matches
        )
        return dedent(f"""\
            # ProtoPatch Fix Notes

            ## Bug Summary
            {bug_analysis.get('bug_description', '')}

            ## Target Element
            `{bug_analysis.get('target_element', '')}`

            ## Suggested Fix
            {bug_analysis.get('suggested_fix', '')}

            ## Affected Files
            {files or '_Unknown_'}

            ## Patch
            ```diff
            {diff or '_No diff generated_'}
            ```

            ---
            _Generated by ProtoPatch v1.0_
        """)
